name: Push Event Workflow

on: push 

jobs:
  unit-testing:
    runs-on: ubuntu-latest 
    
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
      
      - name : Install pipenv
        run : pip install pipenv

      - name: Install dependencies
        run : pipenv sync --dev
        
      - name : Run tests
        working-directory: NextShop
        run : pipenv run pytest --ds=config.settings
