name: Push Event Workflow

on: push 

jobs:
  unit-testing:
    runs-on: ubuntu-latest 
    
    steps:
    - name : Checkout code
      uses : actions/checkout@v2
      
    - name : Install pipenv
      run : pip install pipenv

    - name: Install dependencies
      run : pipenv install

    - name: Active venv
      run : pipenv shell
      
    - name : Run tests 
      run : python -m pytest nextshop --ds=config.settings
